---
resources:
  - name: config-repo
    type: git
    icon: github
    source:
      uri: https://github.com/mitodl/ol-infrastructure.git
      branch: fh/xqueue

  - name: app-repo
    type: git
    icon: github
    source:
      uri: https://github.com/edx/xqueue.git
      branch: master

  - name: image
    type: docker-image
    source:
      repository: ((ecr-uri))

jobs:
  - name: build-push-deploy
    public: true
    serial: true
    plan:
      - get: app-repo
        trigger: true

      - get: config-repo

      - put: image
        params:
          cache: true
          dockerfile: ./config-repo/dockerfiles/xqueue/Dockerfile
          tag_file: ./app-repo/.git/ref
          build: .
          build_args:
            app_dir: app-repo
            config_dir: config-repo/dockerfiles/xqueue

      - task: deploy
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: alpine }
          inputs:
            - name: app-repo
            - name: config-repo
          params:
              AWS_DEFAULT_REGION: us-east-1
          run:
            path: sh
            args:
              - -c
              - |
                set -eux -o pipefail
                apk update
                apk add --no-progress --no-cache aws-cli jq

                FAMILY=xqueue-((environment))
                CLUSTER=edx-ida_((environment))

                aws ecs describe-task-definition --task-definition "${FAMILY}" > deployed-taskdef.json

                TAG=$(head -1 app-repo/.git/ref)

                IMAGE="((ecr-uri)):${TAG}"
                LOG_GROUP=/ecs/((environment))
                TASK_ROLE_ARN=$(< deployed-taskdef.json jq '.taskDefinition.taskRoleArn' -r)
                EXECUTION_ROLE_ARN=$(< deployed-taskdef.json jq '.taskDefinition.executionRoleArn' -r)
                REGION=us-east-1

                sed \
                  -e "s;###IMAGE###;${IMAGE};g" \
                  -e "s;###TASK_ROLE_ARN###;${TASK_ROLE_ARN};g" \
                  -e "s;###EXECUTION_ROLE_ARN###;${EXECUTION_ROLE_ARN};g" \
                  -e "s;###FAMILY###;${FAMILY};g" \
                  -e "s;###NAME###;${FAMILY};g" \
                  -e "s;###LOG_GROUP###;${LOG_GROUP};g" \
                  -e "s;###REGION###;${REGION};g" \
                  -e "s;###ENV###;((environment));g" \
                  -i "config-repo/dockerfiles/xqueue/taskdef.json"
                
                cat config-repo/dockerfiles/xqueue/taskdef.json

                aws ecs register-task-definition --cli-input-json file://config-repo/dockerfiles/xqueue/taskdef.json | tee result.json
                TASK_ARN=$(cat result.json | jq '.taskDefinition.taskDefinitionArn' -r)
                aws ecs update-service --force-new-deployment --service "${FAMILY}" --cluster "${CLUSTER}" --task-definition "${TASK_ARN}"
