{
 "title": "Grafana Usage insights datasource details (Cloud)",
 "description": "Grafana Usage insights datasource details for use with the Loki datasource",
 "tags": [ "grafanacloud" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource" }
  ]
 },
 "panels": [
  {
   "title": "% of error requests ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate({instance_type=\"grafana\"} | logfmt | datasourceName=\"${Datasource}\" | eventName=\"data-request\" | error!=\"\" [$__interval])) / (sum(rate({instance_type=\"grafana\"} | logfmt | datasourceName=\"${Datasource}\" | eventName=\"data-request\" [$__interval])) / 100) "
    }
   ]
  },
  {
   "title": "Total requests ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({instance_type=\"grafana\"} | logfmt | datasourceName=\"${Datasource}\" | eventName=\"data-request\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Datasource requests over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({instance_type=\"grafana\"} | logfmt | eventName=\"data-request\" | datasourceName=\"${Datasource}\" | error = \"\" [$__interval]))",
     "legendFormat": "Data Requests from {{host}}"
    },
    {
     "expr": "sum by(host) (count_over_time({instance_type=\"grafana\"} | logfmt | eventName=\"data-request\" | datasourceName=\"${Datasource}\" | error != \"\" [$__interval]))",
     "legendFormat": "Data Requests errors from {{host}}"
    }
   ]
  },
  {
   "title": "Top 10 error types",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, sum by (error) (count_over_time({instance_type=\"grafana\"} | logfmt | datasourceName=\"${Datasource}\" | error != \"\" [$__interval])))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "95th percentile of request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{instance_type=\"grafana\"} | logfmt | eventName=\"data-request\" | error=\"\" | datasourceName=\"${Datasource}\" | unwrap duration [$__interval]) by (host)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "max(max_over_time({instance_type=\"grafana\"} | logfmt | eventName=\"data-request\" | error=\"\" | datasourceName=\"${Datasource}\" | unwrap duration [$__interval])) by (host)",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "Top 10 users with errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "topk(10, sum by (username) (count_over_time({instance_type=\"grafana\"} | logfmt | datasourceName=\"${Datasource}\" | eventName=\"data-request\" | error!=\"\" [$__interval])))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Top 10 users ",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "topk(10, sum by (username) (count_over_time({instance_type=\"grafana\"} | logfmt | datasourceName=\"${Datasource}\" | eventName=\"data-request\" [$__interval])))",
     "legendFormat": "{{username}}"
    }
   ]
  }
 ]
}