{
 "title": "Usage Insights (Cloud)",
 "description": "This is a Usage Insights dashboard expecting Grafana events in logfmt instead of json.",
 "tags": [ "grafanacloud" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Usage Insight KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total usage insights events  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({instance_type=\"grafana\"}[$__interval])) "
    }
   ]
  },
  {
   "title": "Datasources in use right now",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(sum by (datasourceId) (count_over_time({instance_type=\"grafana\"} | logfmt |  error=\"\" [5m])))  "
    }
   ]
  },
  {
   "title": "Dashboards in use right now",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(sum by (dashboardId) (count_over_time({instance_type=\"grafana\"} | logfmt |  error=\"\" [5m])))"
    }
   ]
  },
  {
   "title": "Users right now",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(sum by (userId) (count_over_time({instance_type=\"grafana\"} | logfmt |  error=\"\" [5m])))"
    }
   ]
  },
  { "title": "Usage Insight Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Usage insights events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({instance_type=\"grafana\"} | logfmt | eventName=\"data-request\" | error = \"\" [$__interval]))",
     "legendFormat": "Data Requests from {{host}}"
    },
    {
     "expr": "sum by(host) (count_over_time({instance_type=\"grafana\"} | logfmt | eventName=\"data-request\" | error != \"\" [$__interval]))",
     "legendFormat": "Data Requests errors from {{host}}"
    },
    {
     "expr": "sum by(host) (count_over_time({instance_type=\"grafana\"} | logfmt | eventName=\"dashboard-view\" [$__interval]))",
     "legendFormat": "Dashboard views from  {{host}}"
    }
   ]
  },
  {
   "title": "Top 10 dashboards",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum by (dashboardId,dashboardName,folderName) (count_over_time({instance_type=\"grafana\"} | logfmt | eventName=\"dashboard-view\" [$__range])))",
     "legendFormat": "{{dashboardName}} - {{folderName}}"
    }
   ]
  },
  {
   "title": "Top 10 data sources",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum by (datasourceName) (count_over_time({instance_type=\"grafana\"} | logfmt | eventName=\"data-request\" [$__range])))",
     "legendFormat": "{{datasourceName}}"
    }
   ]
  },
  {
   "title": "Top 10 users",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum by (username) (count_over_time({instance_type=\"grafana\"} | logfmt | eventName=\"dashboard-view\" [$__range])))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Top 10 dashboards with errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "topk(10, sum by (dashboardId,dashboardName,folderName) (count_over_time({instance_type=\"grafana\"} | logfmt | eventName=\"data-request\" | error!=\"\" [$__range])))",
     "legendFormat": "{{dashboardName}} - {{folderName}}"
    }
   ]
  },
  {
   "title": "Top 10 data sources with errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 21 },
   "targets": [
    {
     "expr": "topk(10, sum by (datasourceName) (count_over_time({instance_type=\"grafana\"} | logfmt | eventName=\"data-request\" | error!=\"\" [$__range])))",
     "legendFormat": "{{datasourceName}}"
    }
   ]
  },
  {
   "title": "Top 10 users seeing errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "expr": "topk(10, sum by (username) (count_over_time({instance_type=\"grafana\"} | logfmt | eventName=\"data-request\" | error!=\"\" [$__range])))",
     "legendFormat": "{{username}}"
    }
   ]
  }
 ]
}