{
 "title": "Grafana Cloud Billing/Usage",
 "tags": [
  "billing",
  "grafanacloud"
 ],
 "time": { "from": "now/M", "to": "now" },
 "panels": [
  { "title": "Billable Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_overage + grafanacloud_org_logs_overage + grafanacloud_org_traces_overage + grafanacloud_org_grafana_overage",
     "legendFormat": "Total additional usage"
    },
    {
     "expr": "grafanacloud_org_spend_commit_credit_total > 0",
     "legendFormat": "Initial spend committed"
    },
    {
     "expr": "grafanacloud_org_spend_commit_balance_total > 0",
     "legendFormat": "Last month spend commit balance"
    }
   ]
  },
  {
   "title": "How Billing Works",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "content": "Metrics, Logs and Traces are billed based on ingestion. For Metrics, we bill based on the number of active series using the 95th percentile during the period. [Learn more here](\nhttps://grafana.com/docs/grafana-cloud/billing-and-usage/)."
  },
  {
   "title": "Current Billable Metrics Series",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_billable_series"
    }
   ]
  },
  {
   "title": "Current Metrics Additional Usage Amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_overage"
    }
   ]
  },
  {
   "title": "Total Billable Metrics Series",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_billable_series",
     "legendFormat": "Billable Series"
    },
    {
     "expr": "grafanacloud_org_metrics_overage",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "grafanacloud_org_metrics_included_series",
     "legendFormat": "Included Series"
    }
   ]
  },
  {
   "title": "Current Billable Logs Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafanacloud_org_logs_usage" }
   ]
  },
  {
   "title": "Current Logs Additional Usage Amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafanacloud_org_logs_overage" }
   ]
  },
  {
   "title": "Total Billable Logs Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    { "expr": "grafanacloud_org_logs_usage", "legendFormat": "Billable Usage" },
    { "expr": "grafanacloud_org_logs_overage", "legendFormat": "Additional Usage Amount" },
    {
     "expr": "grafanacloud_org_logs_included_usage",
     "legendFormat": "Included Usage"
    }
   ]
  },
  {
   "title": "Current Billable Traces Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafanacloud_org_traces_usage" }
   ]
  },
  {
   "title": "Current Traces Additional Usage Amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafanacloud_org_traces_overage"
    }
   ]
  },
  {
   "title": "Total Billable Traces Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    { "expr": "grafanacloud_org_traces_usage", "legendFormat": "Billable Usage" },
    {
     "expr": "grafanacloud_org_traces_overage",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "grafanacloud_org_traces_included_usage",
     "legendFormat": "Included Usage"
    }
   ]
  },
  {
   "title": "Current Billable Grafana Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafanacloud_org_grafana_billable_users"
    }
   ]
  },
  {
   "title": "Current Grafana Additional Usage Amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafanacloud_org_grafana_overage"
    }
   ]
  },
  {
   "title": "Total Billable Grafana Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grafanacloud_org_grafana_billable_users",
     "legendFormat": "Billable Users"
    },
    {
     "expr": "grafanacloud_org_grafana_overage",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "grafanacloud_org_grafana_included_users",
     "legendFormat": "Included Users"
    }
   ]
  },
  { "title": "Metrics Instance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Metrics Active Series",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(grafanacloud_instance_active_series) by (id) * on (id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max(grafanacloud_instance_active_datadog_series > 0) by (id) * on (id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "{{name}} (Datadog series) "
    }
   ]
  },
  {
   "title": "Metrics Ingestion Rate (DPM)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(grafanacloud_instance_samples_per_second * 60) by (id) * on(id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Discarded Metric Samples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "si:/s" }
   ],
   "targets": [
    {
     "expr": "sum(max(grafanacloud_instance_samples_discarded_per_second) by (id, reason)) by (id, reason) * on(id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "{{name}} - {{reason}}"
    }
   ]
  },
  { "title": "Logs Instance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Logs Ingestion Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_logs_instance_bytes_received_per_second) by (id) * on(id) group_left(name) grafanacloud_logs_instance_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Ingested Logs by Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time((grafanacloud_logs_instance_bytes_received_per_second * 60)[1d:1m])) by (id) * on(id) group_left(name) grafanacloud_logs_instance_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Discarded Log Samples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "si:/s" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_logs_instance_samples_discarded_per_second) by (id, reason) * on(id) group_left(name) grafanacloud_logs_instance_info",
     "legendFormat": "{{name}} - {{reason}}"
    }
   ]
  },
  { "title": "Traces Instance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Traces Ingestion Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_traces_instance_bytes_received_per_second) by (id) * on(id) group_left(name) grafanacloud_traces_instance_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Ingested Traces by Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time((grafanacloud_traces_instance_bytes_received_per_second * 60)[1d:1m])) by (id) * on(id) group_left(name) grafanacloud_traces_instance_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Discarded Spans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "si:/s" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_traces_instance_discarded_spans_total:rate5m) by (id, reason) * on(id) group_left(name) grafanacloud_traces_instance_info",
     "legendFormat": "{{name}} - {{reason}}"
    }
   ]
  },
  { "title": "Grafana Instance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Active Grafana Users (last 30 days)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_grafana_instance_active_user_count) by (id) * on(id) group_left(name) grafanacloud_grafana_instance_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Grafana Dashboards",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_grafana_instance_dashboard_count) by (id) * on(id) group_left(name) grafanacloud_grafana_instance_info",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}